<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Com.FPTU.Prn232SE1819.Api.Caching\Com.FPTU.Prn232SE1819.Api.Caching.csproj" />
    <ProjectReference Include="..\Com.FPTU.Prn232SE1819.Api.Infrastructure\Com.FPTU.Prn232SE1819.Api.Infrastructure.csproj" />
    <ProjectReference Include="..\Com.FPTU.Prn232SE1918.Api.Application\Com.FPTU.Prn232SE1918.Api.Application.csproj" />
    <ProjectReference Include="..\Com.FPTU.Prn232SE1918.MssqlServer.Entity\Com.FPTU.Prn232SE1918.Api.MssqlServer.Entity.csproj" />
  </ItemGroup>

</Project>
